[IV-23-34] Objetivo 3
adelahera/basket-stats pull request #22
Opened 2023-11-02 09:39 UTC by adelahera

* [ ] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ ] ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [ ] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [ ] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [ ] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2023-11-03 18:17 UTC, danieeeld2 approved these changes
Buenas, me ha tocado como revisor tuyo. Le acabo de echar un ojillo y, en general, muy bien. Plantas los issues necesarios y los commits son correctos. Si tuviera que decir algo sería poner, a lo mejor un poquito de explicación más sobra make y mage, pero así, tal y como está, lo veo correcto. Buen trabajo compañero 😁:+1:

2023-11-04 09:35 UTC, adelahera commented
> Buenas, me ha tocado como revisor tuyo. Le acabo de echar un ojillo y, en general, muy bien. Plantas los issues necesarios y los commits son correctos. Si tuviera que decir algo sería poner, a lo mejor un poquito de explicación más sobra make y mage, pero así, tal y como está, lo veo correcto. Buen trabajo compañero 😁👍

Muchas gracias! Pues añadida un poco más de información sobre Make y Mage, y lo mando a revisar. A ver qué tal!

2023-11-04 09:37 UTC, adelahera commented
Hola, @JJ. Creo que esto ya está listo para revisar, he recibido el OK de @danieeeld2. ¿O debo esperar a que lo revise algún compañero más?

2023-11-06 08:24 UTC, JJ commented
> Hola, @JJ. Creo que esto ya está listo para revisar, he recibido el OK de @danieeeld2. ¿O debo esperar a que lo revise algún compañero más?

No parece que los haya, así que le echaré un vistazo.

2023-11-06 08:33 UTC, JJ requested changes
El principal problema es la falta de criterios previos a la elección, aunque está bien que hayas hecho un estudio de cómo se gestionaban las dependencias.

2023-11-06 08:33 UTC, JJ commented on doc/gestor_tareas.md
> +En cuanto al task runner, sabemos que hay un montón de opciones diferentes. Voy a describir algunas de las más comunes, y luego, explicar el por qué de mi elección.
Los criterios tienes que exponerlos de antemano. Si no, simplemente escogerás el que mejor te caiga.

2023-11-06 08:33 UTC, JJ commented on doc/sintaxis.md
> +En Go se suele utilizar por defecto la herramienta gofmt, que justamente realiza la función que estamos buscando solventar.
`gofmt`, como su propio nombre indica, formatea, y hace un parsing sintáctico, pero realmente no comprueba si compila o no. Como le he recomendado a @pluque01, [mira esta respuesta en StackOverflow](https://stackoverflow.com/questions/16863014/is-there-a-command-line-tool-in-golang-to-only-check-syntax-of-my-source-code) con las diferentes opciones.

2023-11-06 08:33 UTC, JJ commented on internal/comparacionEstadistica.go
> +func main() {
¿Por qué añades este main?

2023-11-06 08:33 UTC, JJ commented on internal/estadisticasJugador.go
> +	nombreApellidos string
Esto lo estás cambiando porque gofmt es un linter, no un comprobador de sintaxis. Sólo se pide un comprobador de sintaxis.

2023-11-06 08:33 UTC, JJ commented on taskfile.yaml
> +  run:
Supongo que por esto es por lo que haces el `main`. No son necesarios ni el uno ni el otro.

2023-11-06 08:33 UTC, JJ commented on taskfile.yaml
> +      - test -z $(gofmt -l ./internal/)
Buen uso del shell aquí. Pero insisto con el tema de `gofmt`

2023-11-07 07:56 UTC, adelahera commented
Hola, @JJ. Ya he hecho las modificaciones que me sugirió. He decidido eliminar las tareas de run y build, al no ser estrictamente necesarias. Para el comprobador de sintaxis, he leído el enlace de Stackoverflow que me mandó, y he elegido una de las opciones que aparece en el post, aquella que creo únicamente se encarga de comprobar la sintaxis. Por último, he añadido los criterios por los que decidí en su momento que iba a utilizar Task como gestor de tareas.

2023-11-07 08:35 UTC, JJ commented on internal/estadisticasJugador.go
> +	nombreApellidos string
Tendrías que resolver todos los comentarios; este no solicita ninguna modificación, podrías resolverlo directamente.

2023-11-07 08:41 UTC, JJ requested changes
Como sabes, el objetivo de aprendizaje principal aquí es más pragmático, de saber tomar decisiones y documentarlas correctamente. Es importante saberlo, porque es una habilidad que se usa prácticamente en cualquier código que se desarrolle y en cualquier PR que se haga, y especialmente en el resto de los objetivos de la asignatura.
Tomar las decisiones correctamente ayuda a reducir la deuda técnica de un proyecto, y documentarlas correctamente ayuda a que el equipo entienda por qué se ha hecho, aprenda de ello y, en su caso, evolucione hacia otra decisión cambiándola o simplemente manteniendo la decisión hecha. Por eso permitidme que os insista en que debéis hacer este proceso siguiendo una metodología precisa y, una vez más, las mejores prácticas.

2023-11-07 08:41 UTC, JJ commented on doc/gestor_tareas.md
> +- Requiere aprender Make (y además Bash)
Bash lo tienes que aprender en todos. ¿Cómo te crees que ejecuta las cosas npm?

2023-11-07 08:41 UTC, JJ commented on doc/gestor_tareas.md
> +* **Integración con otras herramientas:** como ya sabemos, nuestro proyecto va a ir de la mano de Git, así que vendría muy bien elegir un task runner que se integre bien con Git.
Por favor, mirad [en este archivo de errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-3.md#sobre-los-criterios-para-elegir-las-herramientas) cuantos de esos criterios estáis incluyendo aquí.
En resumen, si no se puede evaluar objetiva (en el sentido de que existan o no existan) y/o numéricamente (este está más integrado en un 40%) no son criterios.

2023-11-07 08:41 UTC, JJ commented on doc/gestor_tareas.md
> +Mage te permite tener varios archivos Mage, nombrarlos como desees y son fáciles de personalizar para múltiples sistemas operativos. Mage no tiene dependencias (a excepción de Go) y funciona perfecta
¿De qué forma decir que permite tener varios archivos contribuye a entender la elección que has hecho? Por favor, [consulta este otro apartado de los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-3.md#sobre-las-herramientas):

> La descripción de las herramientas se debe limitar a la forma en la que siguen los criterios objetivos anteriores y algún otra cualidad que tengan, siempre que se haya enunciado de antemano. Cualquier otra frase sólo añade ruido al PR y no contribuye ni a entender el proceso seguido ni a ayudar al cliente, objetivo último de cualquier proyecto.

2023-11-07 10:38 UTC, adelahera commented on doc/gestor_tareas.md
> +Mage te permite tener varios archivos Mage, nombrarlos como desees y son fáciles de personalizar para múltiples sistemas operativos. Mage no tiene dependencias (a excepción de Go) y funciona perfecta
En esa parte pretendía dar una pequeña introducción a lo que es Mage en sí, no argumentar mi decisión. De hecho, digo que podría haber elegido Mage perfectamente ya que es una muy buena opción, pues es realmente parecido a Task.

2023-11-07 10:42 UTC, adelahera commented
@JJ. He cambiado los criterios, basándome, ahora sí, en aquellos que creo que son completamente cuantificables. Sobre el comentario que me ha puesto sobre Mage, se lo he explicado en la misma conversación, pero por si acaso, lo dejo por aquí también. Esa parte era una breve explicación de cómo funciona Mage y por qué es mejor que Make. Como le he puesto, consideré que Mage y Task son opciones muy parecidas, pero me quedé con Task por su popularidad (tiene más de 5 mil estrellas en Github que el repositorio de Mage)

2023-11-07 11:10 UTC, JJ commented on doc/gestor_tareas.md
> +Mage te permite tener varios archivos Mage, nombrarlos como desees y son fáciles de personalizar para múltiples sistemas operativos. Mage no tiene dependencias (a excepción de Go) y funciona perfecta
¿De veras crees que el que use varios ficheros o uno o ninguno contribuye a justificar la decisión? Esto es solo un ejemplo, la revisión debería ser general y para todas las herramientas.

2023-11-07 11:17 UTC, adelahera commented on doc/gestor_tareas.md
> +Mage te permite tener varios archivos Mage, nombrarlos como desees y son fáciles de personalizar para múltiples sistemas operativos. Mage no tiene dependencias (a excepción de Go) y funciona perfecta
Evidentemente que no me ayuda a tomar la decisión, pero como le he puesto, se trata de una introducción a Mage. Lo que me ayuda a tomar la decisión son los criterios que he especificado y, como le he puesto, Mage es una buena opción porque cumple con los criterios, al igual que Task, solo que esta última parece ser más popular.

2023-11-07 11:18 UTC, JJ requested changes
Conviene tanto que seas preciso con los criterios y como los enuncias como que te ajustes a esos mismos criterios. Gracias por hacer las modificaciones, en todo caso.

2023-11-07 11:18 UTC, JJ commented on doc/gestor_tareas.md
> +Make no se llega a ajustar del todo a los criterios, pues uno de ellos es que sea fácilmente compatible entre sistemas, y hacer un Makefile compatible para muchos sistemas puede ser muy tedioso. Adem
Muchos sistemas, ¿qué?
¿Y el rendimiento?
La facilidad de uso ya no está entre los tres requisitos que has incluido. ¿Y la comunidad? ¿Cuál es la comunidad de make?

2023-11-07 11:18 UTC, JJ commented on doc/gestor_tareas.md
> +* **Rendimiento:** es importante considerar el rendimiento del task runner, es decir, la velocidad y eficiencia con la que ejecuta las tareas. Esto se puede evaluar mediante pruebas de rendimiento y
Este rendimiento es cuantificable, pero efectivamente tendrás que cuantificarlo, es decir, aplicarlo a tu problema en particular.
Y mientras que en general el rendimiento siempre es importante, en este caso que no tienes dependencia entre objetivos y que básicamente se lanza un comando externo, ¿realmente crees que va a haber diferencia?

2023-11-07 11:18 UTC, JJ commented on doc/gestor_tareas.md
> +* **Compatibilidad entre sistemas:** yo mismo trabajo en dos máquinas diferentes, y no tengo el mismo SO en cada una de ellas, así que el task runner debe ser compatible con múltiples SOs para ejecut
A priori, es conveniente que mires [este apartado de los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-3.md#sobre-los-criterios-para-elegir-las-herramientas):

> Si el criterio no se puede evaluar numéricamente de forma que podamos afirmar que uno es mejor que otro en un x%, no son criterios objetivos. Para que quede un poco más claro, no son objetivos: popularidad, facilidad de uso, **compatibilidad**, documentación y en general casi todo lo que se ponga en la segunda revisión una vez que se ha dicho que se deben poner los criterios de elección y tú quieres seguir eligiendo lo mismo que ya has puesto.

Sin embargo, lo que estás diciendo no es exactmente eso. Estás formulando un *requisito* (si no lo tiene, ni se incluye en la lista ni se considera) y este es *que se puedan codificar las tareas en el mismo lenguaje en el que se está trabajando, Go en este caso*. Si  no, ¿cómo va a ser compatible con muchos SOs? El lenguaje debe incluir, por supuesto, todo tipo de primitivas para trabajar con el sistema de ficheros, lanzar programas externos y demás, pero lo tienes que formular con precisión.

Y si ese es el requisito y varias herramientas en Go lo cumplen, *lista sólo esas* y compáralas con respecto a otro criterio, a tu elección (o requisito)

2023-11-07 11:18 UTC, JJ commented on taskfile.yaml
> +      - go mod download
Esta herramienta no cumple el principal requisito que has establecido arriba. Esto son órdenes del shell, exactamente igual que en Make. No es más "compatible" con Windows o con Mac, donde estas órdenes específicas funcionarían exactamente igual.

2023-11-07 11:19 UTC, JJ commented on doc/gestor_tareas.md
> +Mage te permite tener varios archivos Mage, nombrarlos como desees y son fáciles de personalizar para múltiples sistemas operativos. Mage no tiene dependencias (a excepción de Go) y funciona perfecta
Si no te ayuda a tomar la decisión ni a mi a entender por qué la has tomado, ¿crees que debe seguir ahí? ¿Entiendes cuál es el objetivo de los PRs y la razón por la que los reviso, que no es otro que saber si se han alcanzado los objetivos de aprendizaje?

2023-11-07 15:13 UTC, adelahera commented
> Conviene tanto que seas preciso con los criterios y como los enuncias como que te ajustes a esos mismos criterios. Gracias por hacer las modificaciones, en todo caso.

Hola, agradezco mucho sus comentarios para intentar mejorar. Sin embargo, creo que cada comentario me confunde más. Yo estudié las diferentes opciones que tenía, y de esas, descarté Make, por su complejidad y antigüedad. Entre Mage y Task, que son muy parecidas, ya que ambas ofrecen prácticamente lo mismo en cuanto a rendimiento, compatibilidad, etc. , me quedé con Task, porque parece ser que es usado por más usuarios. Ahora bien, parece que no valen ni el criterio de rendimiento, de compatibilidad, de comunidad... ¿Qué quiere que le diga más? No puedo inventarme otros criterios, estudié las opciones (que tengo entendido que es lo de que va el objetivo) y decidí que, entre Task y Mage, me quedaría con Task por número de usuarios. No sé de qué manera documentarlo más para plasmar esto, y que lo entienda.

2023-11-07 16:30 UTC, JJ commented
> > Conviene tanto que seas preciso con los criterios y como los enuncias como que te ajustes a esos mismos criterios. Gracias por hacer las modificaciones, en todo caso.
> 
> Hola, agradezco mucho sus comentarios para intentar mejorar. Sin embargo, creo que cada comentario me confunde más. Yo estudié las diferentes opciones que tenía, y de esas, descarté Make, por su complejidad y antigüedad. Entre Mage y Task, que son muy parecidas, ya que ambas ofrecen prácticamente lo mismo en cuanto a rendimiento, compatibilidad, etc. , me quedé con Task, porque parece ser que es usado por más usuarios, a parte de que, para mí gusto me parecía un poco más intuitivo y sencillo Task. Ahora bien, parece que no valen ni el criterio de rendimiento, de compatibilidad, de facilidad de uso, de comunidad... ¿Qué quiere que le diga más? No puedo inventarme otros criterios. Estudié las opciones (que tengo entendido que es de lo que va el objetivo) y decidí que, entre Task y Mage, me quedaría con Task por número de usuarios y facilidad, como le he dicho. No sé de qué manera documentarlo más para plasmar esto, y que lo entienda.

No te he hecho ningún comentario sobre la elección. Y es que la elección no importa, importa que hayas seguido una metodología correcta para establecer los criterios y aplicarlos a tu caso. Creo que no entiendes que no se trata de que un criterio "valga" o no. Se trata de que estés justificando correctamente la elección. ¿Has usado el rendimiento para elegir ese sistema? ¿Sí? ¿Dónde están las medidas de rendimiento de los expuestos? ¿Has usado la compatibilidad? ¿Sí? ¿Dónde están las tablas en las que la elección hecha supere a otras?

Dices que no puedes inventarte otros criterios, sin embargo, ¿dónde está la prueba de que hayas usado el rendimiento y la compatibilidad para hacer la elección? ¿Las tablas comparativas? 

Se trata simplemente de que hagáis un ejercicio de precisión diciendo de forma precisa por qué has elegido ese y no otro. Si se trata de algo novedoso, que usa un formato estándar (YAML) sencillo de editar o cualquier otro, pues usa eso. No estoy pidiendo más que digáis y justifiquéis por qué habéis elegido lo que habéis hecho.

2023-11-07 18:36 UTC, adelahera commented
> > > Conviene tanto que seas preciso con los criterios y como los enuncias como que te ajustes a esos mismos criterios. Gracias por hacer las modificaciones, en todo caso.
> > 
> > 
> > Hola, agradezco mucho sus comentarios para intentar mejorar. Sin embargo, creo que cada comentario me confunde más. Yo estudié las diferentes opciones que tenía, y de esas, descarté Make, por su complejidad y antigüedad. Entre Mage y Task, que son muy parecidas, ya que ambas ofrecen prácticamente lo mismo en cuanto a rendimiento, compatibilidad, etc. , me quedé con Task, porque parece ser que es usado por más usuarios, a parte de que, para mí gusto me parecía un poco más intuitivo y sencillo Task. Ahora bien, parece que no valen ni el criterio de rendimiento, de compatibilidad, de facilidad de uso, de comunidad... ¿Qué quiere que le diga más? No puedo inventarme otros criterios. Estudié las opciones (que tengo entendido que es de lo que va el objetivo) y decidí que, entre Task y Mage, me quedaría con Task por número de usuarios y facilidad, como le he dicho. No sé de qué manera documentarlo más para plasmar esto, y que lo entienda.
> 
> No te he hecho ningún comentario sobre la elección. Y es que la elección no importa, importa que hayas seguido una metodología correcta para establecer los criterios y aplicarlos a tu caso. Creo que no entiendes que no se trata de que un criterio "valga" o no. Se trata de que estés justificando correctamente la elección. ¿Has usado el rendimiento para elegir ese sistema? ¿Sí? ¿Dónde están las medidas de rendimiento de los expuestos? ¿Has usado la compatibilidad? ¿Sí? ¿Dónde están las tablas en las que la elección hecha supere a otras?
> 
> Dices que no puedes inventarte otros criterios, sin embargo, ¿dónde está la prueba de que hayas usado el rendimiento y la compatibilidad para hacer la elección? ¿Las tablas comparativas?
> 
> Se trata simplemente de que hagáis un ejercicio de precisión diciendo de forma precisa por qué has elegido ese y no otro. Si se trata de algo novedoso, que usa un formato estándar (YAML) sencillo de editar o cualquier otro, pues usa eso. No estoy pidiendo más que digáis y justifiquéis por qué habéis elegido lo que habéis hecho.

Pero es justo eso lo que me está confundiendo. Me ha pedido que utilice criterios que sean evaluables numéricamente, y que además aporte las tablas que aprueben la decisión, cuando, obviamente, ni yo ni ninguno hemos hecho eso. Su última frase, es lo que había hecho primeramente, justificar el por qué de mi decisión (con criterios no evaluables numéricamente). Si eso no es válido y tampoco es válido utilizar criterios que sí son cuantificables porque he de aportar las tablas, cuando ninguno las hemos aportado... es lo que le digo, no sé cómo proceder ahora mismo. No sé qué arreglar, no sé qué está bien, qué está mal...

2023-11-07 18:40 UTC, JJ commented
> > > > Conviene tanto que seas preciso con los criterios y como los enuncias como que te ajustes a esos mismos criterios. Gracias por hacer las modificaciones, en todo caso.
> > > 
> > > 
> > > Hola, agradezco mucho sus comentarios para intentar mejorar. Sin embargo, creo que cada comentario me confunde más. Yo estudié las diferentes opciones que tenía, y de esas, descarté Make, por su complejidad y antigüedad. Entre Mage y Task, que son muy parecidas, ya que ambas ofrecen prácticamente lo mismo en cuanto a rendimiento, compatibilidad, etc. , me quedé con Task, porque parece ser que es usado por más usuarios, a parte de que, para mí gusto me parecía un poco más intuitivo y sencillo Task. Ahora bien, parece que no valen ni el criterio de rendimiento, de compatibilidad, de facilidad de uso, de comunidad... ¿Qué quiere que le diga más? No puedo inventarme otros criterios. Estudié las opciones (que tengo entendido que es de lo que va el objetivo) y decidí que, entre Task y Mage, me quedaría con Task por número de usuarios y facilidad, como le he dicho. No sé de qué manera documentarlo más para plasmar esto, y que lo entienda.
> > 
> > 
> > No te he hecho ningún comentario sobre la elección. Y es que la elección no importa, importa que hayas seguido una metodología correcta para establecer los criterios y aplicarlos a tu caso. Creo que no entiendes que no se trata de que un criterio "valga" o no. Se trata de que estés justificando correctamente la elección. ¿Has usado el rendimiento para elegir ese sistema? ¿Sí? ¿Dónde están las medidas de rendimiento de los expuestos? ¿Has usado la compatibilidad? ¿Sí? ¿Dónde están las tablas en las que la elección hecha supere a otras?
> > Dices que no puedes inventarte otros criterios, sin embargo, ¿dónde está la prueba de que hayas usado el rendimiento y la compatibilidad para hacer la elección? ¿Las tablas comparativas?
> > Se trata simplemente de que hagáis un ejercicio de precisión diciendo de forma precisa por qué has elegido ese y no otro. Si se trata de algo novedoso, que usa un formato estándar (YAML) sencillo de editar o cualquier otro, pues usa eso. No estoy pidiendo más que digáis y justifiquéis por qué habéis elegido lo que habéis hecho.
> 
> Pero es justo eso lo que me está confundiendo. Me ha pedido que utilice criterios que sean evaluables numéricamente, y que además aporte las tablas que aprueben la decisión, cuando, obviamente, ni yo ni ninguno hemos hecho eso. Su 

¿Cuál creéis que es entonces el objetivo de aprendizaje aquí? ¿No es, como en todos, tratar de usar una metodología para llevar a cabo una decisión?

> última frase, es lo que había hecho primeramente, justificar el por qué de mi decisión (con criterios no evaluables numéricamente). Si eso no es válido y tampoco es válido utilizar criterios que sí son cuantificables porque he de aportar las tablas, cuando ninguno las hemos aportado... es lo que le digo, no sé cómo proceder ahora mismo. No sé qué arreglar, no sé qué está bien, qué está mal...

Tenemos un problema, entonces. ¿Cómo crees que podríamos salir del mismo?

2023-11-07 18:48 UTC, adelahera commented
> > > > > Conviene tanto que seas preciso con los criterios y como los enuncias como que te ajustes a esos mismos criterios. Gracias por hacer las modificaciones, en todo caso.
> > > > 
> > > > 
> > > > Hola, agradezco mucho sus comentarios para intentar mejorar. Sin embargo, creo que cada comentario me confunde más. Yo estudié las diferentes opciones que tenía, y de esas, descarté Make, por su complejidad y antigüedad. Entre Mage y Task, que son muy parecidas, ya que ambas ofrecen prácticamente lo mismo en cuanto a rendimiento, compatibilidad, etc. , me quedé con Task, porque parece ser que es usado por más usuarios, a parte de que, para mí gusto me parecía un poco más intuitivo y sencillo Task. Ahora bien, parece que no valen ni el criterio de rendimiento, de compatibilidad, de facilidad de uso, de comunidad... ¿Qué quiere que le diga más? No puedo inventarme otros criterios. Estudié las opciones (que tengo entendido que es de lo que va el objetivo) y decidí que, entre Task y Mage, me quedaría con Task por número de usuarios y facilidad, como le he dicho. No sé de qué manera documentarlo más para plasmar esto, y que lo entienda.
> > > 
> > > 
> > > No te he hecho ningún comentario sobre la elección. Y es que la elección no importa, importa que hayas seguido una metodología correcta para establecer los criterios y aplicarlos a tu caso. Creo que no entiendes que no se trata de que un criterio "valga" o no. Se trata de que estés justificando correctamente la elección. ¿Has usado el rendimiento para elegir ese sistema? ¿Sí? ¿Dónde están las medidas de rendimiento de los expuestos? ¿Has usado la compatibilidad? ¿Sí? ¿Dónde están las tablas en las que la elección hecha supere a otras?
> > > Dices que no puedes inventarte otros criterios, sin embargo, ¿dónde está la prueba de que hayas usado el rendimiento y la compatibilidad para hacer la elección? ¿Las tablas comparativas?
> > > Se trata simplemente de que hagáis un ejercicio de precisión diciendo de forma precisa por qué has elegido ese y no otro. Si se trata de algo novedoso, que usa un formato estándar (YAML) sencillo de editar o cualquier otro, pues usa eso. No estoy pidiendo más que digáis y justifiquéis por qué habéis elegido lo que habéis hecho.
> > 
> > 
> > Pero es justo eso lo que me está confundiendo. Me ha pedido que utilice criterios que sean evaluables numéricamente, y que además aporte las tablas que aprueben la decisión, cuando, obviamente, ni yo ni ninguno hemos hecho eso. Su
> 
> ¿Cuál creéis que es entonces el objetivo de aprendizaje aquí? ¿No es, como en todos, tratar de usar una metodología para llevar a cabo una decisión?
> 
> > última frase, es lo que había hecho primeramente, justificar el por qué de mi decisión (con criterios no evaluables numéricamente). Si eso no es válido y tampoco es válido utilizar criterios que sí son cuantificables porque he de aportar las tablas, cuando ninguno las hemos aportado... es lo que le digo, no sé cómo proceder ahora mismo. No sé qué arreglar, no sé qué está bien, qué está mal...
> 
> Tenemos un problema, entonces. ¿Cómo crees que podríamos salir del mismo?

No lo sé, yo siento que he intentado aplicar la metodología, primero de una forma, y luego de otra, y ninguna es válida, seguramente porque me esté perdiendo algo, pero no sé el qué. Lo hablamos el jueves y quizás me pueda explicar mejor, pero de verdad, no sé qué me estoy perdiendo.

2023-11-07 18:50 UTC, JJ commented
Por lo pronto, ¿entiendes los comentarios que he hecho? ¿Te parecen lo suficientemente concretos como para trabajar en ellos?

2023-11-07 18:53 UTC, adelahera commented
> Por lo pronto, ¿entiendes los comentarios que he hecho? ¿Te parecen lo suficientemente concretos como para trabajar en ellos?

Sí, los comentarios los entiendo. Lo que no entiendo es en qué es incorrecto lo que he ido enviando. Como le he dicho, me he ido ajustando a lo que me ha ido diciendo. Como comprenderá, cuando no sé qué es incorrecto, no puedo solucionar nada.

2023-11-07 19:03 UTC, JJ commented
> > Por lo pronto, ¿entiendes los comentarios que he hecho? ¿Te parecen lo suficientemente concretos como para trabajar en ellos?
> 
> Sí, los comentarios los entiendo.

¿Te parece entonces empezar  por reaccionar a esos comentarios, adaptando el contenido si lo ves conveniente? Si hay algo que no entiendes o no entiendes por qué es incorrecto, simplemente solicita aclaración. Precisamente los PRs se comentan en línea para que esté claro el contexto y a qué se refiere.

2023-11-07 21:15 UTC, adelahera commented
Bueno, @JJ . Le he dado otra vuelta más, a ver si ahora he acertado. He decidido los criterios para que todos puedan ser evaluados numéricamente, y basar la decisión en esta evaluación. Gracias por la ayuda.

2023-11-08 06:40 UTC, JJ approved these changes
:+1:

2023-11-08 11:12 UTC, merged