[IV-23-24] Objetivo 1
adelahera/basket-stats pull request #5
Opened 2023-09-22 09:36 UTC by adelahera

Sobre los milestones

* [x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [x] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [x] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [x] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [x] ¿El milestone 0 es mínimo *y* viable?
* [x] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?
    
Sobre las historias de usuario

* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [x] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [x] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2023-09-25 11:51 UTC, JJ commented
Apreciaría que contestaras, aunque fuera brevemente, los items de la lista de comprobación. Realmente me harían más fácil evaluar (y a vosotros comprobar si efectivamente cumple lo pedido)

2023-09-25 11:57 UTC, JJ requested changes
Lo más importante en los milestones es identificar claramente el producto a entregar. En las historias de usuario, hacerlas lo suficientemente atómicas para que cada una tenga un solo "ojalá".

2023-09-25 11:57 UTC, JJ commented on doc/historias_usuario.md
> +Como periodista deportivo especializado en baloncesto, quiero una herramienta en línea que me permita comparar las estadísticas de los jugadores de baloncesto de diferentes épocas. También me gustarí
"También" no cabe en una historia de usuario. Cada historia de usuario es un solo "ojalá" de un usuario.

2023-09-25 11:57 UTC, JJ commented on doc/historias_usuario.md
> +Las estadísticas que más me interesan son: partidos jugados, minutos jugados, puntos, rebotes ofensivos, rebotes defensivos, asistencias, robos, tapones, pérdidas, porcentaje de tiro de dos puntos, p
En lo posible, debes abstenerte de decir qué es lo que se debe usar para solucionar el problema. Si le "interesan" esas estadísticas eso puede ser una historia de usuario (también diferente), pero el que se use eso y no otra cosa es algo que se tiene que decidir durante el desarrollo.
Por ponerte un caso, los minutos jugados y puntos puede que no sean tan interesantes como el número de puntos por minuto jugado, o el número de minutos jugados en partidos en los que fue convocado (sin lesiones o cosas así). No debes *nunca* prever qué hay que hacer para solucionar el problema, la ingeniería es la que tiene que decidirlo.

2023-09-25 11:57 UTC, JJ commented on doc/milestones.md
> +Identificación y priorización de las historias de usuario necesarias para el desarrollo del proyecto.
Las historias de usuario ya están priorizadas por el número; "identificación" tampoco es unp roducto. Tendrás que especificar claramente qué te tiene que entregar quien desarrolle en este milestone.

2023-09-25 11:57 UTC, JJ commented on doc/milestones.md
> +- ### Milestone 1: Investigación de las fuentes de datos disponibles
Un milestone no es nunca una tarea.
Y las fuentes de datos se supone que debes tenerlas tú por tu conocimiento del problema.

2023-09-26 07:54 UTC, adelahera commented
@JJ listo para revisión. Además, me ha surgido una duda sobre un comentario que me has dado sobre las historias de usuario. ¿Un usuario no puede requerir más de una cosa de la aplicación? ¿No puede tener más de 1 deseo , u "ojalás" como lo has llamado, que lo cumpla la app? Lo he corregido, pero no tengo muy claro por qué no podría pedir más de 1 cosa a la app.

Muchas gracias.

2023-09-26 07:56 UTC, JJ commented
> @JJ listo para revisión. Además, me ha surgido una duda sobre un comentario que me has dado sobre las historias de usuario. ¿Un usuario no puede requerir más de una cosa de la aplicación? ¿No puede tener más de 1 deseo , u "ojalás" como lo has llamado, que lo cumpla la app? Lo he corregido, pero no tengo muy claro por qué no podría pedir más de 1 cosa a la app.

Sí, pero las historias de usuario son documentos de trabajo. Si hay muchas cosas que hacer, el documento para explicarlas es el *user journey*; ese documento luego se plasma en diferentes historias de usuario. Dado que las HUs sirven para organizar el trabajo y priorizar el desarrollo de un deseo del usuario frente a otro, meterlas todas en el mismo realmente no ayuda.

2023-09-26 08:03 UTC, JJ requested changes
Las historias de usuario deben tener también un número de orden, que correspondan al orden de trabajo en la aplicación.

En este caso, sugeriría que alguna de las personas que han pasado el objetivo, @luciaansino o @manuelvico0102 (o ambos) lo revisaran antes de que me lo pases a revisión por una segunda vuelta.

2023-09-26 08:03 UTC, JJ commented on doc/historias_usuario.md
> +Como periodista deportivo especializado en baloncesto, quiero una herramienta en línea que me permita comparar las estadísticas de los jugadores de baloncesto de diferentes épocas. Me gustaría poder
Como os he comentado, una HU es un documento de trabajo. Si no específicas qué quieres decir con estadísticas, estás dejando para la etapa siguiente averiguar con qué datos se cuenta y saber de qué tipo son. Todas las historias de usuario tienen que añadir un contexto que sirva para modelizar el problema en la etapa siguiente.

2023-09-26 08:03 UTC, JJ commented on doc/milestones.md
> +Comprender las historias de usuario para familiriazarse con el problema a resolver.
¿Qué es el "diseño del modelo del problema"? También: typo 
¿Cuando es ese diseño válido?

2023-09-26 08:03 UTC, JJ commented on doc/milestones.md
> +Implementar el código necesario para obtener los datos de las fuentes de datos seleccionadas.
Si el problema es la obtención de datos, la historia de usuario debe explicar que ese es el problema.

2023-09-26 08:34 UTC, manuelvico0102 commented on doc/historias_usuario.md
> +Como fanático apasionado de la NBA, quiero una aplicación en línea que me permita acceder fácilmente a las estadísticas de mis jugadores favoritos, pudiendo ordenar los jugadores en orden creciente o
A esta historia de usuario le haría falta más contexto sobre que información se va a trabajar para la estadística, así como explicar como funcionaría la estadística como ha mencionado el profesor.

2023-09-26 08:34 UTC, manuelvico0102 commented on doc/milestones.md
> +PMV: Código que resuelva la obtención de datos desde las fuente de datos seleccionadas.
En este milestone también te haría falta indicar la forma de que sea viable este milestone.

2023-09-26 20:24 UTC, adelahera commented on doc/historias_usuario.md
> +Como periodista deportivo especializado en baloncesto, quiero una herramienta en línea que me permita comparar las estadísticas de los jugadores de baloncesto de diferentes épocas. Me gustaría poder
En el commit anterior incluía en esta historia de usuario las estadísticas con las que iba a trabajar, pues eran las que interesaban al cliente. Eliminé esa parte porque me comentó que no debería incluir lo que debo usar para el desarrollo. Sin embargo, este comentario ahora me ha dejado descolocado, ¿debo incluir los datos que interesan al cliente? Algo me estoy perdiendo.

2023-09-26 20:48 UTC, adelahera commented on doc/milestones.md
> +Implementar el código necesario para obtener los datos de las fuentes de datos seleccionadas.
En cuanto a esto, el problema no es la obtención de la datos. Sin embargo, es una parte esencial de la solución. La idea de que fuera un milestone por sí misma es justamente por eso, por su importancia y porque además permite ver al cliente como va progresando la app. Se puede entregar al cliente este milestone, y a partir de ahí, añadir otros milestones sobre este. Como decir: ya tenemos acceso y podemos trabajar con todos los datos que necesitamos. A partir de aquí, podemos ir haciendo el resto de la aplicación.

2023-09-27 05:27 UTC, JJ commented on doc/historias_usuario.md
> +Como periodista deportivo especializado en baloncesto, quiero una herramienta en línea que me permita comparar las estadísticas de los jugadores de baloncesto de diferentes épocas. Me gustaría poder
Una cosa es que especifiques qué quiere el cliente que debe tener la solución (que no debe hacerlo, sólo decir qué quiere obtenerlo) y otra que especifiques el contexto *para el programador* para que este sepa qué datos tiene y con cuales puede contar. Al final, se trata de tener datos para crear un modelo. ¿Te parece que "estadísticas" sea suficiente para hacerlo?
En general, las historias de usuario siguen el modelo "dado que ... como ... quiero obtener... o si no...". El "Dado que" aquí es lo esencial, porque indica el contexto.

2023-09-27 05:30 UTC, JJ commented on doc/milestones.md
> +Implementar el código necesario para obtener los datos de las fuentes de datos seleccionadas.
No puedes hacer un milestone sin abordar una historia de usuario. Si es parte esencial de la solución, es decir, si necesitas hacer algo no trivial para obtener los datos, tienes que incluirlo en una historia de usuario.

2023-09-27 11:18 UTC, adelahera commented
> Las historias de usuario deben tener también un número de orden, que correspondan al orden de trabajo en la aplicación.
> 
> En este caso, sugeriría que alguna de las personas que han pasado el objetivo, @LuciaAnsino o @manuelvico0102 (o ambos) lo revisaran antes de que me lo pases a revisión por una segunda vuelta.

2023-09-27 11:24 UTC, adelahera commented
@LuciaAnsino @manuelvico0102 he seguido las recomendaciones que me propusisteis, tanto vosotros como JJ. Creo que ahora está mejor, ¿podéis echarle un vistazo antes de mandarlo a revisar a JJ? Tal y como me propuso él. 

Muchas gracias.

2023-09-27 15:35 UTC, manuelvico0102 commented
Creo que lo has pulido bastante bien, así que creo que el profesor puede pasar a revisarlo.

2023-09-27 15:43 UTC, JJ commented
> Creo que lo has pulido bastante bien, así que creo que el profesor puede pasar a revisarlo.

Por favor, acéptalo explícitamente en la solapa "files" botón "Review". Cuando @adelahera quiera, que me pida revisión.

2023-09-27 16:15 UTC, manuelvico0102 approved these changes

2023-09-27 16:16 UTC, adelahera commented on doc/milestones.md
> +# Milestones
Resuelto. He creado un milestone adicional

2023-09-27 16:21 UTC, adelahera commented
> Ni @LuciaAnsino lo ha aceptado, ni has hecho nada con respecto al comentario que te ha hecho. Si lo has hecho modificando otra línea, puedes "resolver" el comentario diciendo algo así como "resuelto en xxxx " (hash del commit que puedes copiar y pegar).
> 
> Conviene que cuando se hagan revisiones se actúe sobre todas y cada una de ellas.

Sí he seguido la recomendación de Lucía, he creado un milestone adicional, tal y como me había dicho. No lo había resuelto porque no sabía que tenía que hacerse así. Ahora sí está resuelto. ¿Qué debo hacer entonces, espero a Lucía o lo mando a revisión?

2023-09-27 17:13 UTC, LuciaAnsino approved these changes

2023-09-27 17:21 UTC, JJ requested changes
Agradezco a @LuciaAnsino y @manuelvico0102 el trabajo realizado, creo que podrías darle una vuelta al tema de la ordenación, es decir, priorización, de las HUs y milestones, así como a qué es realmente el milestone cero.

2023-09-27 17:21 UTC, JJ commented on doc/historias_usuario.md
> +Dado mi fanatismo por la NBA, quiero obtener una aplicación que me permita interactuar con las estadísticas de mis jugadores favoritos. Me gustaría poder ordenarlas en orden creciente o decreciente,
Tienes que numerar las historais de usuario, para que se vea claramente cuál ea la prioridad.
Por otro lado, todas las HUs, o al menos las que vas a emprender en esta asignatura, tienen que tener relación con la lógica de negocio. Aquí no veo lo que hablamos en clase, sino una simple búsqueda u ordenación. En general, la HU1 será con la que trabajes en esta asignatura. Por eso ver esta como la primera no está claro que evidencie que estás priorizando lo que se va a hacer en la asignatura.

2023-09-27 17:21 UTC, JJ commented on doc/milestones.md
> +- ### M0: Comprensión del problema.
Tendrás que comprenderlo lo suficiente para hacer un modelo del mismo, ¿no?

2023-09-27 17:21 UTC, JJ commented on doc/milestones.md
> +- ### M1: Implementación de los filtros sobre la base de datos
Como te he comentado arriba, el primer milestone tiene que corresponder al objetivo 4, es decir, a la implementación de una lógica de negocio. Un filtro no es suficiente para esta lógica de negocio.

2023-09-28 17:15 UTC, adelahera commented
@JJ listo para revisión. He optado por ajustarme a lo que va a ser mi lógica de negocio, y por ello, he eliminado una de las historias de usuario, al ver que no se ajustaba plenamente a lo que se pretende del proyecto.

2023-09-28 17:40 UTC, JJ approved these changes
:basketball: Pero, insisto, la historia de usuario, aunque sea una sola, tiene que tener un número; luego puede haber más o no, es una cuestión formal.

2023-09-29 07:30 UTC, merged