[IV-23-24] Objetivo 7
adelahera/basket-stats pull request #62
Opened 2023-12-19 22:17 UTC by adelahera

## Issues
* Closes #54 

## Lista de comprobación
* [ ] ¿Se han registrado todos los eventos relevantes en la aplicación, es decir, se
  han añadido comandos para registrarlos en todos ellos?
* [ ] ¿Se han seguido buenas prácticas en el uso de configuración remota?
* [ ] ¿Se han explicado correctamente las decisiones técnicas que se han tomado
  sobre las bibliotecas usadas?
* [ ] ¿Te has asegurado de que el fichero `.env` no se pueda añadir
accidentalente al repositorio?
* [ ] ¿Los logs y la configuración están en un objeto que se *inyecta* en las
clases manejadoras para su uso?
* [ ] ¿*Realmente* se usan los logs en las diferentes clases en eventos
importantes?
* [ ] ¿Se testea el código creado para logs y configuración, igual que
    cualquier otro código?
* [ ] ¿La clase o módulo de configuración lee *siempre* las variables de entorno?

2023-12-20 11:57 UTC, pluque01 reviewed
Hola! 
Te he puesto algunos comentarios sobre tu código, de todas formas el trabajo es muy completo. Ánimo!

2023-12-20 11:57 UTC, pluque01 commented on doc/logger.md
> +### Log
Pon enlaces a la web de cada uno de los módulos :))

2023-12-20 11:57 UTC, pluque01 commented on internal/comparacion_estadistica/comparacion_estadistica.go
> +		logger.Info().Msg("El jugador " + clave.nombreApellidos + " no existe en la epoca " + strconv.Itoa(epoca.fechaInicio))
Igual este tipo de mensajes podrían ser de tipo Debug, pero tampoco creo que esté mal si son de tipo Info

2023-12-20 11:57 UTC, pluque01 commented on internal/comparacion_estadistica/comparacion_estadistica.go
> +		logger.Error().Msg("Error al calcular la variación de las estadísticas:" + err.Error())
Bien usados los errores de Go para luego mostrarlos con el logger 👍

2023-12-20 11:57 UTC, pluque01 commented on internal/comparacion_estadistica/comparacion_estadistica.go
>  		return nil, errors.New("error al normalizar las estadísticas")
Aquí realmente estás repitiendo el error. La llamada al logger debería hacerse desde la función que llame a comparaJugadores, y meter al logger el posible error que devuelva la función.

2023-12-20 11:57 UTC, pluque01 commented on internal/config/config.go
> +var Conf *Config
Si tienes un método GetConfig que ya gestiona cuando y como se devuelve esta variable, deberías de ponerla en minúscula para que no se exporte y pueda ser accedida de forma incorrecta.

2023-12-20 16:47 UTC, adelahera commented on doc/logger.md
> +### Log
Arreglado en [79fd4e0](https://github.com/adelahera/basket-stats/pull/62/commits/79fd4e09fb437c629fb33864bb449ab5b2084ebc) y en [ca83a8a](https://github.com/adelahera/basket-stats/pull/62/commits/ca83a8a36e1e7d936bcc2bf0e12d8f054c688bff)

2023-12-20 16:48 UTC, adelahera commented on internal/comparacion_estadistica/comparacion_estadistica.go
> +		logger.Info().Msg("El jugador " + clave.nombreApellidos + " no existe en la epoca " + strconv.Itoa(epoca.fechaInicio))
Pues sí, tienes razón. Creo que tendría más sentido si fueran de tipo Debug. Arreglado en [1d374a5](https://github.com/adelahera/basket-stats/pull/62/commits/1d374a549a5e0a87a9fa4a7bf3e037d353c3197b)

2023-12-20 16:48 UTC, adelahera commented on internal/comparacion_estadistica/comparacion_estadistica.go
> +		logger.Error().Msg("Error al calcular la variación de las estadísticas:" + err.Error())
Gracias!! ❤️

2023-12-20 16:49 UTC, adelahera commented on internal/comparacion_estadistica/comparacion_estadistica.go
>  		return nil, errors.New("error al normalizar las estadísticas")
Tienes razón. Arreglado en [17f4b0c](https://github.com/adelahera/basket-stats/pull/62/commits/17f4b0cb7c0917e180bae111e5d25e95c57818e2)

2023-12-20 16:49 UTC, adelahera commented on internal/config/config.go
> +var Conf *Config
Sí, esto se me había pasado. Arreglado en [62ff2cb](https://github.com/adelahera/basket-stats/pull/62/commits/62ff2cb2ff750e101549bac78169643651c591a1)

2023-12-20 16:52 UTC, pluque01 approved these changes
Veo que has corregido lo que te comenté.
Yo lo veo listo para revisión. :))

2023-12-21 08:09 UTC, adelahera commented
@JJ listo para revisión.

2023-12-21 08:45 UTC, JJ requested changes
El principal problema es la inclusión de bibliotecas que posiblemente no correspondan a lo que se busca en este objetivo. También se deberían abreviar las descripciones, a lo estricto para entender la elección. El resto es un poco más optativo. Y gracias a @pluque01 por la revisión.

2023-12-21 08:45 UTC, JJ commented on doc/sistemas_configuracion.md
> +[Cobra](https://github.com/spf13/cobra) es una biblioteca que proporciona una interfaz sencilla para crear potentes interfaces de línea de comandos (CLI) modernas, similares a las de herramientas com
Pero ¿tiene en cuenta también los ficheros de configuración o sólo los de línea de órdenes?

2023-12-21 08:45 UTC, JJ commented on doc/sistemas_configuracion.md
> +- Integración opcional y sin problemas con Viper.
¿Y crees que corresponde a la denominación genérica de ficheros de configuración de la que hablamos aquí?

2023-12-21 08:45 UTC, JJ commented on internal/comparacion_estadistica/comparacion_estadistica.go
> +			logger.Info().Msg("Campo " + campo + " no está en el CSV")
¿Estás haciendo logging independientemente del nivel que se haya establecido? Por otro lado, ¿podría tener esto más sentido con un nivel DEBUG?

2023-12-21 08:45 UTC, JJ commented on internal/comparacion_estadistica/comparacion_estadistica.go
> +		logger.Info().Msg("Perdidas normalizadas a " + strconv.Itoa(jugador.perdidas))
Estás usando `strconv.Itoa` repetidamente. ¿No has considerado crear un objeto que envuelva esto y haga las conversiones automáticamente?

2023-12-22 08:26 UTC, adelahera commented on doc/sistemas_configuracion.md
> +[Cobra](https://github.com/spf13/cobra) es una biblioteca que proporciona una interfaz sencilla para crear potentes interfaces de línea de comandos (CLI) modernas, similares a las de herramientas com
He eliminado la opción de Cobra e incluido otras opciones. Arreglado en [e9841f0](https://github.com/adelahera/basket-stats/pull/62/commits/e9841f02b606caec4dcc7a158084b5f2f9197442)

2023-12-22 08:27 UTC, adelahera commented on doc/sistemas_configuracion.md
> +- Integración opcional y sin problemas con Viper.
[e9841f0](https://github.com/adelahera/basket-stats/pull/62/commits/e9841f02b606caec4dcc7a158084b5f2f9197442)

2023-12-22 08:27 UTC, adelahera commented on internal/comparacion_estadistica/comparacion_estadistica.go
> +		logger.Info().Msg("Perdidas normalizadas a " + strconv.Itoa(jugador.perdidas))
Arreglado en [517ee56](https://github.com/adelahera/basket-stats/pull/62/commits/517ee56e2c92ebd46488726efd6beff2818b2969)

2023-12-22 09:19 UTC, JJ reviewed
👍

2023-12-22 17:37 UTC, merged