[IV-23-24] Objetivo 8
adelahera/basket-stats pull request #69
Opened 2023-12-30 21:06 UTC by adelahera

## Issues
* Closes #68 

## Lista de comprobación

* [ ] ¿Has justificado tu elección de un framework REST y explicado por qué no has
   elegido ni `flask` ni `express`?
* [ ] ¿Las rutas están organizadas alrededor de un recurso?
* [ ] ¿Has usado cada verbo HTTP con su forma convencional más aceptada?

2024-01-01 18:40 UTC, pluque01 requested changes
Hola!
Te he dejado una sugerencia, míralo cuando puedas :))

2024-01-01 18:40 UTC, pluque01 commented on internal/api/api.go
> +	app.Delete("/borrar/:temporada/:jugador", deleteJugador)
No creo que estés orientando las rutas sobre el recurso. Las rutas deberían crearse alrededor del recurso y usar los verbos de HTTP para gestionar que tipo de acción se debe realizar. En este caso podría ser `app.Delete("/:temporada/:jugador", deleteJugador)`

2024-01-01 18:40 UTC, pluque01 commented on internal/api/api.go
> +	app.Delete("/borrar/:epoca", deleteEpoca)
En estos lo mismo que te he comentado antes.

2024-01-01 19:30 UTC, adelahera commented on internal/api/api.go
> +	app.Delete("/borrar/:temporada/:jugador", deleteJugador)
Sí, había malentendido ese concepto. Arreglado en [7deb563](https://github.com/adelahera/basket-stats/pull/69/commits/7deb56380f8fd5f1861dcc02d8931c42a1407b63)

2024-01-01 19:31 UTC, adelahera commented on internal/api/api.go
> +	app.Delete("/borrar/:epoca", deleteEpoca)
Arreglado en [7deb563](https://github.com/adelahera/basket-stats/pull/69/commits/7deb56380f8fd5f1861dcc02d8931c42a1407b63)

2024-01-01 20:05 UTC, pluque01 approved these changes
Yo lo veo bien, te he hecho una pequeña sugerencia pero te doy el visto bueno

2024-01-01 20:05 UTC, pluque01 commented on internal/api/api.go
> +	app.Delete("/jugador/:temporada/:nombre", deleteJugadorTemporada)
Yo cambiaría esta ruta para que fuera `/jugador/:nombre/:temporada`, así tendría más sentido con la siguiente.

2024-01-01 20:06 UTC, pluque01 commented on internal/api/api.go
> +	app.Delete("/jugador/:temporada/:nombre", deleteJugadorTemporada)
O incluso todas en las que haya temporadas poner el nombre primero

2024-01-01 20:11 UTC, adelahera commented on internal/api/api.go
> +	app.Delete("/jugador/:temporada/:nombre", deleteJugadorTemporada)
Gracias por la sugerencia. Arreglado en [a2e9f9c](https://github.com/adelahera/basket-stats/pull/69/commits/a2e9f9c5be0256601881deccb84e49aa695535de)

2024-01-04 16:42 UTC, adelahera commented
@JJ, puede echarle un vistazo cuando pueda? Muchas gracias 😃

2024-01-04 19:16 UTC, JJ requested changes
Bastante completo, pero convendría que le dieras una vuelta al diseño de los URIs

2024-01-04 19:16 UTC, JJ commented on internal/api/api.go
> +	app.Delete("/estadisticas/:nombre/:temporada", deleteEstadisticas)
¿Qué necesidad hay de borrarlas?

2024-01-04 19:16 UTC, JJ commented on internal/api/api.go
> +	app.Post("/jugador", addJugador)
Tendrías que definir cuál es el URI de cada jugador, o de cada recurso. Si, como parece, es jugador/:nombre/:temporada, ya conoces el URI y por tanto ¿no sería mejor usar PUT en vez de POST?

2024-01-05 09:39 UTC, adelahera commented on internal/api/api.go
> +	app.Post("/jugador", addJugador)
Tuve esa misma duda mientras diseñaba las URIs. Al final me decanté por usar POST precisamente porque no conozco la URI del jugador, por eso la ruta es solo /jugador , ya que del jugador que se va a crear no conozco todavía ni su nombre ni la temporada. Es algo que me generó dudas en su momento, así que quizá tenga razón, pero no lo llego a entender del todo.

2024-01-05 09:42 UTC, adelahera commented on internal/api/api.go
> +	app.Delete("/estadisticas/:nombre/:temporada", deleteEstadisticas)
En esto estoy de acuerdo, quizá no sea necesario. Arreglado en [91cec83](https://github.com/adelahera/basket-stats/pull/69/commits/91cec830dd66e9a088ba732f3705397e8c253a54)

2024-01-05 09:55 UTC, JJ commented on internal/api/api.go
> +	app.Post("/jugador", addJugador)
¿Cómo puede ser que no lo conozcas? ¿Con qué parámetros lo creas entonces?

2024-01-05 10:02 UTC, adelahera commented on internal/api/api.go
> +	app.Post("/jugador", addJugador)
Pues los parámetros parar crear al jugador irían en el body, ¿o es incorrecto de esa forma?

2024-01-05 10:07 UTC, JJ commented on internal/api/api.go
> +	app.Post("/jugador", addJugador)
Los parámetros podrán ir en el body, pero lo que forme parte del URI (que parece ser el nombre y el periodo) es mejor que sean parte del mismo URI. Puedes usar PUT también, como siempre que se conoce el URI.

2024-01-05 10:21 UTC, adelahera commented on internal/api/api.go
> +	app.Post("/jugador", addJugador)
Una última duda en ese caso. Si utilizo PUT y el URI /jugador/:nombre/:temporada, sería la misma ruta que utilizo para actualizar los datos del jugador (la última ruta, que se encarga de actualizar datos de un jugador) ¿Cómo diferencio una ruta de la otra?

2024-01-05 10:29 UTC, JJ commented on internal/api/api.go
> +	app.Post("/jugador", addJugador)
Si se actualiza parcialmente debes usar `PATCH`, si lo actualizas completo, simplemente usa PUT de nuevo.

2024-01-05 10:36 UTC, adelahera commented on internal/api/api.go
> +	app.Post("/jugador", addJugador)
Entendido. Arreglado en [419a721](https://github.com/adelahera/basket-stats/pull/69/commits/419a721881a2cefabd4b8c2b8e0cb3dc7b2a70cc)

2024-01-06 17:42 UTC, adelahera commented
@JJ , entonces... ¿el objetivo estaría superado?

2024-01-06 17:57 UTC, JJ commented
Me temo que no, el estado es todavía "suggested changes...". ¿Estás pidiendo revisión?

2024-01-06 18:03 UTC, adelahera commented
> Me temo que no, el estado es todavía "suggested changes...". ¿Estás pidiendo revisión?

Efectivamente, se trataba de la revisión. Lo hago explícitamente.

2024-01-06 18:35 UTC, JJ approved these changes
:+1:

2024-01-06 18:56 UTC, merged